### ISSUE TITLE
Always receive 2085 UNKNOWN_OBJECT_NAME error on PCF commands

### ISSUE THREAD

**Issue by Bbouch** [dsuch/pymqi#18]
import pymqi, CMQC
from CMQCFC import *

queue_manager = "MYQUEUEMANAGER"
channel = "MONITOR.SVRCONN"
host = "syse.myhost.com"
port = "1414"
conn_info = "%s(%s)" % (host, port)

qmgr = pymqi.connect(queue_manager, channel, conn_info)
pcf = pymqi.PCFExecute(qmgr)
pcf.MQCMD_PING_Q_MGR()
qmgr.disconnect()

I'm able to connect to my queue manager (at least i am not getting an error when trying), but when I execute the PCF ping command, I'm getting the following exception:

[mqm@fgl-dv-agt01 tmp]$ python btest.py
Traceback (most recent call last):
  File "btest.py", line 12, in <module>
    pcf.MQCMD_PING_Q_MGR()
  File "/usr/lib64/python2.6/site-packages/pymqi-1.4-py2.6-linux-x86_64.egg/pymqi.py", line 2365, in **call**
    raise MQMIError(rv[-2], rv[-1])
pymqi.MQMIError: MQI Error. Comp: 2, Reason 2085: FAILED: MQRC_UNKNOWN_OBJECT_NAME

Not sure what I am doing wrong here. Thoughts?
(I'm using pymqi 1.3 on Linux, connecting to MQ 7.5)

**Comment by dsuch** [comment]
Hm, the only MQ object used in this code snippet is the ```MONITOR.SVRCONN``` channel. Are you 100% sure it exists?

**Comment by dsuch** [comment]
Closing due to inactivity - please reopen if needed, thanks!
