### ISSUE TITLE
Problem with refresh security type SSL

### ISSUE THREAD

**Issue by JochemGit** [dsuch/pymqi#194]
I just implemented command REFRESH SECURITY. The first two seem to work. With type SSL I receive an exception about a not available message.

Source code:
```
def refreshSecurity(MQIACF_SECURITY_TYPE, pcfHandle):
    cmdArgs = {pymqi.CMQCFC.MQIACF_SECURITY_TYPE: MQIACF_SECURITY_TYPE}
    print(str(cmdArgs))
    printPcfCmd(cmdArgs)
    pcfHandle.MQCMD_REFRESH_SECURITY(cmdArgs)

def refreshSecurityAUTHSERV(pcfHandle):
    refreshSecurity(pymqi.CMQCFC.MQSECTYPE_AUTHSERV, pcfHandle)

def refreshSecurityCONNAUTH(pcfHandle):
    refreshSecurity(pymqi.CMQCFC.MQSECTYPE_CONNAUTH, pcfHandle)

def refreshSecuritySSL(pcfHandle):
    refreshSecurity(pymqi.CMQCFC.MQSECTYPE_SSL, pcfHandle)

```
Output:
```
{1106: 1}
MQIACF_SECURITY_TYPE: MQSECTYPE_AUTHSERV

{1106: 4}
MQIACF_SECURITY_TYPE: MQSECTYPE_CONNAUTH

{1106: 2}
MQIACF_SECURITY_TYPE: MQSECTYPE_SSL

Traceback (most recent call last):
  File "./queue.py", line 895, in <module>
    refreshSecuritySSL(pcf)
  File "./queue.py", line 826, in refreshSecuritySSL
    refreshSecurity(pymqi.CMQCFC.MQSECTYPE_SSL, pcfHandle)
  File "./queue.py", line 817, in refreshSecurity
    pcfHandle.MQCMD_REFRESH_SECURITY(cmdArgs)
  File "/usr/local/lib/python3.6/dist-packages/pymqi-1.10.1-py3.6-linux-x86_64.egg/pymqi/__init__.py", line 2674, in __call__
    message = self.__pcf._reply_queue.get(None, get_md, get_opts)
  File "/usr/local/lib/python3.6/dist-packages/pymqi-1.10.1-py3.6-linux-x86_64.egg/pymqi/__init__.py", line 1976, in get
    raise MQMIError(rv[-2], rv[-1], message=rv[0], original_length=rv[-3])
pymqi.MQMIError: MQI Error. Comp: 2, Reason 2033: FAILED: MQRC_NO_MSG_AVAILABLE
```

Do you have an idea, what is the problem?

**Comment by SeyfSV** [comment]
@JochemGit , try to increase wait interval.
Current master version does not support it :) ([info](https://github.com/dsuch/pymqi/issues/191#issuecomment-635940997))

I you already use new branch, then add `response_wait_interval` attribute to `PCFExecute` call (constructor). response_wait_interval - is tens of second. Default value is 100 (10 seconds)
```
pcf = pymqi.PCFExecute(qmgr, response_wait_interval=600) # 1 minute
```

**Comment by JochemGit** [comment]
Yes, you know, I used it already. :)

Thank you! It works, now!
