### ISSUE TITLE
ModuleNotFoundError: No module named 'pymqe'

### ISSUE THREAD

**Issue by slanky2** [dsuch/pymqi#200]
Hello,

I have tried extensively to get this working over the last day with no luck.

pip install reports success but I still get the error:

```
/IdeaProjects/mq-test/venv/bin/python /IdeaProjects/mq-test/handler.py
Traceback (most recent call last):
  File "/IdeaProjects/mq-test/venv/lib/python3.7/site-packages/pymqi/__init__.py", line 128, in <module>
    from . import pymqe
ImportError: dlopen(/IdeaProjects/mq-test/venv/lib/python3.7/site-packages/pymqi/pymqe.cpython-37m-darwin.so, 2): Library not loaded: @rpath/libmqic_r.dylib
  Referenced from: /IdeaProjects/mq-test/venv/lib/python3.7/site-packages/pymqi/pymqe.cpython-37m-darwin.so
  Reason: image not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/IdeaProjects/mq-test/handler.py", line 1, in <module>
    import pymqi
  File "/IdeaProjects/mq-test/venv/lib/python3.7/site-packages/pymqi/__init__.py", line 130, in <module>
    import pymqe  # Backward compatibility
ModuleNotFoundError: No module named 'pymqe'

Process finished with exit code 1
```

**Comment by slanky2** [comment]
Yes I have the bin in my path.  I have found that the code works fine from the command line but I still get the error if run from the IDE (IntelliJ).  I am a novice Python developer.

**Comment by AlexandreYang** [comment]
I'm developing on MacOS too and getting a similar issue. What works for me is using a virtualenv, but not sure why it doesn't work without the virtualenv in my case under similar conditions. 

### Does not work without virtualenv
```
$ export DYLD_LIBRARY_PATH=/opt/mqm/lib64

$ python --version
Python 3.8.1

$ python -m pip freeze | grep pymqi
pymqi==1.11.1

$ python -c 'import pymqi'   # does not work without virtualenv
Traceback (most recent call last):
  File "XXXXXXX/.pyenv/versions/3.8.1/lib/python3.8/site-packages/pymqi/__init__.py", line 129, in <module>
    from . import pymqe # type: ignore
ImportError: dlopen(XXXXXXX/.pyenv/versions/3.8.1/lib/python3.8/site-packages/pymqi/pymqe.cpython-38-darwin.so, 2): Library not loaded: @rpath/libmqic_r.dylib
  Referenced from: XXXXXXX/.pyenv/versions/3.8.1/lib/python3.8/site-packages/pymqi/pymqe.cpython-38-darwin.so
  Reason: image not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "XXXXXXX/.pyenv/versions/3.8.1/lib/python3.8/site-packages/pymqi/__init__.py", line 131, in <module>
    import pymqe # type: ignore # Backward compatibility
ModuleNotFoundError: No module named 'pymqe'
```

### Works with virtualenv
```
$ export DYLD_LIBRARY_PATH=/opt/mqm/lib64

$ virtualenv venv3

$ source venv3/bin/activate

(venv3) $ python --version
Python 3.8.1

(venv3) $ pip install pymqi

(venv3) $ pip freeze pymqi
pymqi==1.11.1

(venv3) $ python -c 'import pymqi'  # works
```

**Comment by SeyfSV** [comment]
On VS Code I set PYTHONPATH (use .env files with it and other variables):
```
PYTHONPATH=/xxxxx/code:/xxxxx/pymqi/code/build/lib.linux-x86_64-3.7/pymqi:code/tests
```
Path is specific for python version

**Comment by SeyfSV** [comment]
@slanky2 , did you resolve issue? Can we close it?

**Comment by AlexandreYang** [comment]
Looks like it's due to MacOS ["Runtime Protections"](https://developer.apple.com/library/archive/documentation/Security/Conceptual/System_Integrity_Protection_Guide/RuntimeProtections/RuntimeProtections.html#//apple_ref/doc/uid/TP40016462-CH3-SW1):

> Any dynamic linker (dyld) environment variables, such as DYLD_LIBRARY_PATH, are purged when launching protected processes.

The runtime protection is effect on python directly executed on MacOS.

`pymqi` is working when using a virtualenv because this runtime protection does not purge DYLD_LIBRARY_PATH in that case.

```
# no virtualenv
$ DYLD_LIBRARY_PATH=/opt/mqm/lib64 python -c 'import os; print(os.environ.get("DYLD_LIBRARY_PATH"))'
None

# inside virtualenv
§ DYLD_LIBRARY_PATH=/opt/mqm/lib64 python -c 'import os; print(os.environ.get("DYLD_LIBRARY_PATH"))'
/opt/mqm/lib64
```

**Comment by rjseibert** [comment]
I use mac with this library.  For what it it is worth, I believe these should be prerequisites:

```
  * Install MQ Client
  * Reinstall with `pip install --no-cache-dir pymqi` if the install has been attempted without MQ Client already installed.
  * Set env vars `MQ_INSTALLATION_PATH=/opt/mqm` and `DYLD_LIBRARY_PATH='$MQ_INSTALLATION_PATH/lib64'`
```
