### ISSUE TITLE
pymqe.so: failed to map segment from shared object

### ISSUE THREAD

**Issue by z710x40** [dsuch/pymqi#226]
L.S.

I've got a:

-bash-4.2$ python mq_ing_agent.py
Traceback (most recent call last):
  File "mq_ing_agent.py", line 1, in <module>
    from pymqi import *
  File "build/bdist.linux-x86_64/egg/pymqi/__init__.py", line 134, in <module>
  File "build/bdist.linux-x86_64/egg/pymqi/pymqe.py", line 7, in <module>
  File "build/bdist.linux-x86_64/egg/pymqi/pymqe.py", line 6, in __bootstrap__
ImportError: /home/mqm/.python-eggs/pymqi-1.11.1-py2.7-linux-x86_64.egg-tmp/pymqi/pymqe.so: failed to map segment from shared object: Operation not permitted

I get the error when I install pymqi via pip for python 2 and 3. What causes this issue?

Erwin

**Comment by dsuch** [comment]
Hello Erwin,

you have not provided any details of your operating system - please post the output from at least **uname -a** and **lsb_release -a**.

From what I can see for now, it looks that you have SELinux, grsecurity or a similar low-level mechanism enabled and it is not configured to allow PyMQI to run.

From an operating system's perspective, PyMQI is a shared library and the system is not allowing you to load it.

**Comment by dsuch** [comment]
Another idea is that you perhaps installed PyMQI as one user and run it as another where some permissions are denied to the latter.

Generally, this is not something caused by PyMQI itself so you need to investigate it yourself primarily.

**Comment by dsuch** [comment]
Thanks, I understand it. Just please observe that it is the operating system that does not allow you to run a PyMQI program, i.e. this is not an issue in PyMQI.

Are you a developer using the system or its administrator (since you have root)?

The message you are receiving "failed to map segment from shared object: Operation not permitted" comes from Linux, not from PyMQI. I recommend that you search the web for other occurrences of this error and try to follow the solutions found.

Once you have it working, please post your solution here for the benefit of other users.

Just remember that from the system's perspective, PyMQI is a dynamically loaded shared library written in C, this is key, because your it is your system does not allow you to load PyMQI - in other words, you are not getting any error from PyMQI here, PyMQI is not even loaded yet when this message is returned.

**Comment by dsuch** [comment]
No activity, closing the ticket.
