### ISSUE TITLE
Unexplainable error when using the Filter class on Debian 10 with python 2.7.16

### ISSUE THREAD

**Issue by fschaeck** [dsuch/pymqi#228]
I got some strange "attribute not found" errors on self.pub_filter.operator when using the Filter class with an integer filter on the number of messages in a queue. After changing the FilterOperator and Filter classes to basically move the operator name into the FilterOperator class and get rid of the Filter object in the FilterOperator, everything worked fine.

The attached file contains the diff against 1.12.0 code as available on pypi.org

[pymqi-1.12.0a.patch.tar.gz](https://github.com/dsuch/pymqi/files/5236674/pymqi-1.12.0a.patch.tar.gz)

**Comment by SeyfSV** [comment]
Hi @fschaeck,
Can you show code that raise the error and stack trace?
Does the IDE (which one) get an error in debug mode or only when running the .py file?

**Comment by fschaeck** [comment]
Hi @SeyfSV,

Well... I just installed the original code of PyMQI and checked with Eclipse IDE 2020-06 with PyDev 7.7.0 the following code:

```
import sys
import argparse
from pymqi import QueueManager,CMQC,CMQCFC,MQMIError,PCFExecute,Filter

def getListOfNonEmptyLocalQueues(qmgrName):
    try:
        pcf = None
        queueName = '*'.encode()
        queueType = CMQC.MQQT_LOCAL
        queueDepthFilter = Filter(CMQC.MQIA_CURRENT_Q_DEPTH).greater(0)

        pcfArgs = {CMQC.MQCA_Q_NAME: queueName,
                   CMQC.MQIA_Q_TYPE: queueType,
                   CMQCFC.MQIACF_Q_ATTRS : CMQC.MQCA_Q_NAME}
    
        qmgrHndl = QueueManager(qmgrName) # running in bind mode!
        pcf  = PCFExecute(qmgrHndl,dynamic_queue_name=b'PYMQI.*')
        response = pcf.MQCMD_INQUIRE_Q(pcfArgs,[ queueDepthFilter ])
    except MQMIError as e:
        if pcf is not None:
            pcf.disconnect()
        if e.comp == CMQC.MQCC_FAILED and e.reason == CMQC.MQRC_UNKNOWN_OBJECT_NAME:
            return []
        else:
            raise
    else:
        pcf.disconnect()
        return (queueInfo[CMQC.MQCA_Q_NAME].strip() for queueInfo in response)

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('qmgr',
                        metavar='<qmgr>',
                        type=str,
                        help='name of queue manager to run against')
    arguments = vars(parser.parse_args())
    
    for qName in getListOfNonEmptyLocalQueues(arguments['qmgr']):
        sys.stdout.write(qName+'\n')
```
Running it inside Eclipse and on command line everything is fine. But debugging it step-by-step in Eclipse, the following exception  is thrown:

```
Traceback (most recent call last):
  File "/opt/eclipse-2020-03/plugins/org.python.pydev.core_7.7.0.202008021154/pysrc/pydevd.py", line 3206, in <module>
    main()
  File "/opt/eclipse-2020-03/plugins/org.python.pydev.core_7.7.0.202008021154/pysrc/pydevd.py", line 3199, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/opt/eclipse-2020-03/plugins/org.python.pydev.core_7.7.0.202008021154/pysrc/pydevd.py", line 2273, in run
    return self._exec(is_module, entry_point_fn, module_name, file, globals, locals)
  File "/opt/eclipse-2020-03/plugins/org.python.pydev.core_7.7.0.202008021154/pysrc/pydevd.py", line 2280, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/user/Development/DZ-Bank/hg/mqjournal_api_exit/mqjournal_python/src/testGetListOfNonEmptyQueues.py", line 43, in <module>
    for qName in getListOfNonEmptyLocalQueues(arguments['qmgr']):
  File "/home/user/Development/DZ-Bank/hg/mqjournal_api_exit/mqjournal_python/src/testGetListOfNonEmptyQueues.py", line 15, in getListOfNonEmptyLocalQueues
    queueDepthFilter = Filter(CMQC.MQIA_CURRENT_Q_DEPTH).greater(0)
  File "build/bdist.linux-x86_64/egg/pymqi/__init__.py", line 2622, in __call__
pymqi.Error: Operator [__class__] is not supported.
```

My changed code allows stepping through it as well - without exception. So I guess the problem isn't with PyMQI but with the Eclipse debugger...

Regards, Frank

**Comment by fschaeck** [comment]
Just updated Eclipse to 2020-09 and PyDev to 8.0.0, but the error when debugging with the original code still happens.

**Comment by SeyfSV** [comment]
Yes :) I know about this issue, I got it in VS Code too.
Thank you for patch! I merged it to master.
I you have no other questions, please close the issue.
