### ISSUE TITLE
AIX 7.1 MQRCCF_CFH_LENGTH_ERROR when query queues

### ISSUE THREAD

**Issue by maaiika** [dsuch/pymqi#263]
I can normally find queues on Linux, but I can't find queues on AIX 7.1. What's the difference between the struclength of Aix and Linux
the wmq version is 7.5 both Linux Aix

```
     def _discover_queues(self, queue_manager, mq_pattern_filter, config):
            queues = []
            for queue_type in SUPPORTED_QUEUE_TYPES:
                args = {pymqi.CMQC.MQCA_Q_NAME: pymqi.ensure_bytes(
                    mq_pattern_filter), pymqi.CMQC.MQIA_Q_TYPE: queue_type}
                try:
                    pcf = pymqi.PCFExecute(
                        queue_manager, convert=config.convert_endianness)
                    response = pcf.MQCMD_INQUIRE_Q(args)
                except pymqi.MQMIError as e:
                    self.log.warning(
                        "Error discovering queue_type: %s queue: %s %s maybe this queue not exists" %
                        (queue_type, mq_pattern_filter, e))
                    pass
                else:
                    for queue_info in response:
                        queue = queue_info[pymqi.CMQC.MQCA_Q_NAME]
                        queues.append(str(queue).strip())
            self.log.debug('get queues useing pattern `%s` ,'
                           'resoult {}'.format(queues) % mq_pattern_filter)
            return queues
```

> 

```
2021-05-19 11:06:23,477 | WARNING | dd.collect | checks.IbmMq(wmq.py:594) | Error discovering queue_type: 1 queue: Q1 MQI Error. Comp: 2, Reason 3002: FAILED: MQRCCF_CFH_LENGTH_ERROR maybe this queue not exists
2021-05-19 11:06:23,501 | WARNING | dd.collect | checks.IbmMq(wmq.py:594) | Error discovering queue_type: 2 queue: Q1 MQI Error. Comp: 2, Reason 3002: FAILED: MQRCCF_CFH_LENGTH_ERROR maybe this queue not exists
2021-05-19 11:06:23,525 | WARNING | dd.collect | checks.IbmMq(wmq.py:594) | Error discovering queue_type: 3 queue: Q1 MQI Error. Comp: 2, Reason 3002: FAILED: MQRCCF_CFH_LENGTH_ERROR maybe this queue not exists
2021-05-19 11:06:23,549 | WARNING | dd.collect | checks.IbmMq(wmq.py:594) | Error discovering queue_type: 6 queue: Q1 MQI Error. Comp: 2, Reason 3002: FAILED: MQRCCF_CFH_LENGTH_ERROR maybe this queue not exists
2021-05-19 11:06:23,577 | WARNING | dd.collect | checks.IbmMq(wmq.py:594) | Error discovering queue_type: 7 queue: Q1 MQI Error. Comp: 2, Reason 3002: FAILED: MQRCCF_CFH_LENGTH_ERROR maybe this queue not exists
```

when i useing linux to connet aix wmq errors

```
021-05-19 15:11:50,724 | ERROR | dd.collect | checks.IbmMq(wmq.py:331) | cannot connect to queue manager: Unpack for type ((67108864,)) not implemented
Traceback (most recent call last):
  File "/opt/ant-agent/agent/extension/thirdmods/local-monitor/agent/checks_d/wmq.py", line 327, in check_wmq
    self.check_queues(queue_manager, config.channel, config)
  File "/opt/ant-agent/agent/extension/thirdmods/local-monitor/agent/checks_d/wmq.py", line 304, in check_queues
    match_queues = self.get_match_queues(queue_manager, config)
  File "/opt/ant-agent/agent/extension/thirdmods/local-monitor/agent/checks_d/wmq.py", line 420, in get_match_queues
    all_queues = self._discover_queues(queue_manager, '*', config)
  File "/opt/ant-agent/agent/extension/thirdmods/local-monitor/agent/checks_d/wmq.py", line 590, in _discover_queues
    response = pcf.MQCMD_INQUIRE_Q(args)
  File "/opt/ant-agent/agent/embedded/lib/python2.7/site-packages/pymqi/__init__.py", line 2776, in __call__
    res, mqcfh_response = self.__pcf.unpack(message)
  File "/opt/ant-agent/agent/embedded/lib/python2.7/site-packages/pymqi/__init__.py", line 3015, in unpack
    raise NotImplementedError('Unpack for type ({}) not implemented'.format(pcf_type))
NotImplementedError: Unpack for type ((67108864,)) not implemented
```

**Comment by SeyfSV** [comment]
Hi @maaiika, there are no differences in structure for AIX and Linux, but there is difference in endian.
You use:
```
                pcf = pymqi.PCFExecute(
                    queue_manager, convert=config.convert_endianness)
```
what is the value of convert_endianness in AIX and Linux environments (in case of error)

**Comment by maaiika** [comment]
hi, @SeyfSV 
convert_endianness is a default value False
when True error logs:
`2021-05-24 10:17:51,374 | DEBUG | dd.collect | checks.IbmMq(wmq.py:506) | try connecting queue_manager:QM1 channel:CH1,with a username and password
True
2021-05-24 10:17:51,420 | WARNING | dd.collect | checks.IbmMq(wmq.py:596) | Error discovering queue_type: 1 queue: * MQI Error. Comp: 33554432, Reason -1173684224: FAILED: Error code -1173684224 not defined maybe this queue not exists
True
2021-05-24 10:17:51,449 | WARNING | dd.collect | checks.IbmMq(wmq.py:596) | Error discovering queue_type: 2 queue: * MQI Error. Comp: 33554432, Reason -1173684224: FAILED: Error code -1173684224 not defined maybe this queue not exists
True
2021-05-24 10:17:51,477 | WARNING | dd.collect | checks.IbmMq(wmq.py:596) | Error discovering queue_type: 3 queue: * MQI Error. Comp: 33554432, Reason -1173684224: FAILED: Error code -1173684224 not defined maybe this queue not exists
True
2021-05-24 10:17:51,505 | WARNING | dd.collect | checks.IbmMq(wmq.py:596) | Error discovering queue_type: 6 queue: * MQI Error. Comp: 33554432, Reason -1173684224: FAILED: Error code -1173684224 not defined maybe this queue not exists
True
2021-05-24 10:17:51,529 | WARNING | dd.collect | checks.IbmMq(wmq.py:596) | Error discovering queue_type: 7 queue: * MQI Error. Comp: 33554432, Reason -1173684224: FAILED: Error code -1173684224 not defined maybe this queue not exists
2021-05-24 10:17:51,529 | DEBUG | dd.collect | checks.IbmMq(wmq.py:603) | get queues useing pattern `*` ,resoult []
2021-05-24 10:17:51,530 | DEBUG | dd.collect | checks.IbmMq(wmq.py:440) | get useing config.queues `[]` ,resoult {}
2021-05-24 10:17:51,530 | DEBUG | dd.collect | checks.IbmMq(wmq.py:450) | all queues `[]`
2021-05-24 10:17:51,530 | DEBUG | dd.collect | checks.IbmMq(wmq.py:451) | match queues `set([])`
True
2021-05-24 10:17:51,556 | WARNING | dd.collect | checks.IbmMq(wmq.py:369) | Error getting CHANNEL status for channel SYSTEM.AUTO.SVRCONN: MQI Error. Comp: 33554432, Reason -1173684224: FAILED: Error code -1173684224 not defined
True
2021-05-24 10:17:51,584 | WARNING | dd.collect | checks.IbmMq(wmq.py:369) | Error getting CHANNEL status for channel CH2: MQI Error. Comp: 33554432, Reason -1173684224: FAILED: Error code -1173684224 not defined
True
2021-05-24 10:17:51,608 | WARNING | dd.collect | checks.IbmMq(wmq.py:369) | Error getting CHANNEL status for channel SYSTEM.DEF.SVRCONN: MQI Error. Comp: 33554432, Reason -1173684224: FAILED: Error code -1173684224 not defined
True
2021-05-24 10:17:51,632 | WARNING | dd.collect | checks.IbmMq(wmq.py:369) | Error getting CHANNEL status for channel CH1: MQI Error. Comp: 33554432, Reason -1173684224: FAILED: Error code -1173684224 not defined`

**Comment by SeyfSV** [comment]
Ok, let's clarify:
what value do you use and what is happened:
* client on Linux -> server on Linux (in this case you should use convert_endianness=False, and this works as I understand)
* client on Linux -> server on AIX (in this case you should use convert_endianness=True, and this case should work)
* client on AIX -> server on AIX (I think it should return `MQRCCF_CFH_LENGTH_ERROR`, see below)

I have no access to AIX (big-endian OS), and can't test `pymqi` on it, but I am afraid, that issue in `mqmd.encoding` field. `pymqi` uses `0x00000222` value for `MQENC_NATIVE`, but for running program on AIX it should be `0x00000111` (https://www.ibm.com/docs/en/ibm-mq/9.2?topic=constants-mqenc-encoding).
Can you change `MQENC_NATIVE` to `0x00000111` in `CMQC.py` file before running code on AIX?

**Comment by maaiika** [comment]
Thank you very much for your help, when i chanage MQENC_NATIVE, all problems are solved。


I don't know the platform name, cpu arch such as Z/OS、IBM® i , so I have to use a brutal way:
```
if platform.system() == 'Linux' or platform.system() == 'Windows':
    MQENC_NATIVE = 0x00000222
elif platform.system() == 'AIX':
    MQENC_NATIVE = 0x00000111
```

**Comment by SeyfSV** [comment]
@maaiika , if you wish you can provide PR for this issue.
For info #166 about pymqi and AIX :)
