### ISSUE TITLE
What MQ Files need to be included to run PYMQI independent of installing the full MQ?

### ISSUE THREAD

**Issue by ryanhartlee** [dsuch/pymqi#271]
Trying to run a script using PYMQI on a VM. I'm trying to see if i can pull the MQ dll's so I dont have to install the whole MQ client, since its heavy. I am getting:

```Traceback (most recent call last):
  File "C:\Users\241812\AppData\Local\Programs\Python\Python39\lib\site-packages\pymqi\__init__.py", line 133, in <module>
    from . import pymqe # type: ignore

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Work\GH\gm-web-gateevents\main.py", line 1, in <module>
    import pymqi
  File "C:\Users\241812\AppData\Local\Programs\Python\Python39\lib\site-packages\pymqi\__init__.py", line 135, in <module>
    import pymqe # type: ignore # Backward compatibility
ModuleNotFoundError: No module named 'pymqe'```

**Comment by JoshMcMQ** [comment]
Look for the IBM MQ Redist client for this purpose.   9.2 Redist also includes the header files so you should be able to compile against it.

**Comment by ryanhartlee** [comment]
So for using the redist package, when installing PYMQI, how do we tell it to use the redist and not the installed MQ client? PYMQI searches for the installs from the env variables.

**Comment by SeyfSV** [comment]
Use `MQ_FILE_PATH` env variable

**Comment by ryanhartlee** [comment]
> Use `MQ_FILE_PATH` env variable

Are you saying replace that env variable search with the file path of the redist?

**Comment by ryanhartlee** [comment]
> > Use `MQ_FILE_PATH` env variable
> 
> Are you saying replace that env variable search with the file path of the redist?

It worked. Thanks.

**Comment by ryanhartlee** [comment]
We get this message when we compile the working files into an exe. We include all necessary pip packages, the redist, etc. 
``` Traceback (most recent call last):
  File "main.py", line 15, in <module>
  File "pymqi\__init__.py", line 3027, in connect
  File "pymqi\__init__.py", line 1652, in connect_tcp_client
  File "pymqi\__init__.py", line 1627, in connect_with_options
pymqi.MQMIError: MQI Error. Comp: 2, Reason 2012: FAILED: MQRC_ENVIRONMENT_ERROR
[25512] Failed to execute script 'main' due to unhandled exception!
``` any ideas now? Its acting like the credentials would be wrong but they work when running the py file on its own
