### ISSUE TITLE
MQ 8.0 and wrong ELFCLASS32

### ISSUE THREAD

**Issue by pkaczynski** [dsuch/pymqi#54]
I installed MQ 8.0 on Ubuntu Linux x64. MQ series is working just fine and installation of pymqi went without any warnings. However, after import of pyqm I get the following error:

```bash
Python 2.7.12 (default, Nov 19 2016, 06:48:10)
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pymqi
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pkaczynski/pythonenv/local/lib/python2.7/site-packages/pymqi/__init__.py", line 109, in <module>
    import pymqe, CMQC, CMQCFC, CMQXC
ImportError: libmqic_r.so: wrong ELF class: ELFCLASS32
```
Is this MQ series or pymqi problem? Or maybe my config is wrong somehow?

**Comment by pkaczynski** [comment]
My mistake in python verision.
