### ISSUE TITLE
Blank password gives Unauthorised user error

### ISSUE THREAD

**Issue by deliego** [dsuch/pymqi#74]
Hi there!,

I am currently using PyMQI 1.7.2 and having issues with authentication when a password is not provided.

There are cases where it fine to provide a username but no password. I'm trying to do the same using pymqi but I keep getting the Unauthorized user error. In the examples, I see connecting without user/password or with it, but not "with user/no password".

MQ is configured with AUTHTYPE(IDPWOS) CHCKCLNT(OPTIONAL) so it is able to handle no user/password (check AMQERR01 log below)

I have a Java application connected to the same MQ with a user but no password (empty string '') so I was able to test  that the user and MQ is properly configured.

I have used the default pymqi example to connect to MQ with a user and a blank password (empty string '') and the error is still:
\pymqi\\__init__.py", line 1412, in connectWithOptions\n raise MQMIError(rv[1], rv[2])\npymqi.MQMIError: MQI Error. Comp: 2, Reason 2035: FAILED: MQRC_NOT_AUTHORIZED\n

To summarize:
- PyMQI version: 1.7.2 
- Password: ''
- Same user used on other apps and they log in fine.
- Code tested with password first, then used User Accounts to configure "ibmmquser" account to remove password ("No password" in config screen) and to recreate the issue.
- Simple code to get queue depth: 
```
import pymqi

queue_manager = 'QM_ORANGE'
channel = 'QM_ORANGE.QM_APPLE'
host = '127.0.0.1'
port = '1415'
queue_name = 'QM_APPLE'
conn_info = '%s(%s)' % (host, port)
user = 'ibmmquser'
password = ''

qmgr = pymqi.connect(queue_manager, channel, conn_info, user, password)

args = {pymqi.CMQC.MQCA_Q_NAME : queue_name,
		pymqi.CMQCFC.MQIACF_Q_ATTRS : pymqi.CMQC.MQIA_CURRENT_Q_DEPTH}
pcf = pymqi.PCFExecute(qmgr)
print(pcf.MQCMD_INQUIRE_Q(args))

qmgr.disconnect()
```
- Result:
```
Traceback (most recent call last):
  File "get_q_depth.py", line 12, in <module>
    qmgr = pymqi.connect(queue_manager, channel, conn_info, user, password)
  File "/usr/local/lib/python3.6/dist-packages/pymqi/__init__.py", line 2530, in connect
    qmgr.connect_tcp_client(queue_manager or '', CD(), channel, conn_info, user, password)
  File "/usr/local/lib/python3.6/dist-packages/pymqi/__init__.py", line 1430, in connectTCPClient
    self.connectWithOptions(name, cd, user=user, password=password)
  File "/usr/local/lib/python3.6/dist-packages/pymqi/__init__.py", line 1412, in connectWithOptions
    raise MQMIError(rv[1], rv[2])
pymqi.MQMIError: MQI Error. Comp: 2, Reason 2035: FAILED: MQRC_NOT_AUTHORIZED
```

- AMQERR01.LOG:
```
2018-08-19 01:59:43 PM - Process(2730.21064) User(diego) Program(amqzlaa0)
                    Host(diego-VirtualBox) Installation(Installation1)
                    VRMF(9.0.5.0) QMgr(QM_ORANGE)
                    Time(2018-08-19T17:59:43.401Z)
                    CommentInsert1(ibmmquser)
                    CommentInsert2(python)
                    CommentInsert3(N/A)

AMQ5534E: User ID 'ibmmquser' authentication failed

EXPLANATION:
The user ID and password supplied by the 'python' program could not be
authenticated.
Additional information: 'N/A'.
ACTION:
Ensure that the correct user ID and password are provided by the application.
Ensure that the authentication repository is correctly configured. Look at
previous error messages for any additional information.
----- amqzfuca.c : 4495 -------------------------------------------------------
2018-08-19 01:59:43 PM - Process(2730.21064) User(diego) Program(amqzlaa0)
                    Host(diego-VirtualBox) Installation(Installation1)
                    VRMF(9.0.5.0) QMgr(QM_ORANGE)
                    Time(2018-08-19T17:59:43.401Z)
                    CommentInsert1(ibmmquser)
                    CommentInsert2(SYSTEM.DEFAULT.AUTHINFO.IDPWOS)
                    CommentInsert3(CHCKCLNT(OPTIONAL))

AMQ5542I: The failed authentication check was caused by the queue manager
CONNAUTH CHCKCLNT(OPTIONAL) configuration.

EXPLANATION:
The user ID 'ibmmquser' and its password were checked because the queue manager
connection authority (CONNAUTH) configuration refers to an authentication
information (AUTHINFO) object named 'SYSTEM.DEFAULT.AUTHINFO.IDPWOS' with
CHCKCLNT(OPTIONAL).

This message accompanies a previous error to clarify the reason for the user ID
and password check.
ACTION:
Refer to the previous error for more information.

Ensure that a password is specified by the client application and that the
password is correct for the user ID. The authentication configuration of the
queue manager connection determines the user ID repository. For example, the
local operating system user database or an LDAP server.

If the CHCKCLNT setting is OPTIONAL, the authentication check can be avoided by
not passing a user ID across the channel. For example, by omitting the MQCSP
structure from the client MQCONNX API call.

To avoid the authentication check, you can amend the authentication
configuration of the queue manager connection, but you should generally not
allow unauthenticated remote access.
```

Thanks!,

Diego

**Comment by dsuch** [comment]
Hello @deliego,

I have just checked it with PyMQI 1.8.0 under Wireshark and I can confirm that no password is being sent if it is an empty string on input to pymqi.connect even if there is a username.

I wonder if in the Java application there is a difference between setting a password to null vs. to an empty string?

If upgrading to 1.8.0 does not help, please let me know what the exact runmqsc commands to recreate your MQ configuration are.

Thanks.

**Comment by dsuch** [comment]
@JoshMcMQ - this all very interesting and I have just one question, when CSPPasswordPtr in MQCSP is NULL in C terms, which then translates to no password being sent along with the username, this lone username is then checked against which attribute of which MQ object as far as MQSC commands go?

**Comment by JoshMcMQ** [comment]
I have never tested that exact configuration, but I think it is likely it would fail since if you have CONNAUTH enabled, by having MQCSP.AuthenticationType set to MQCSP_AUTH_USER_ID_AND_PWD you indicate you want mq to check the username and password presented.

In any case, even when CONNAUTH succeeds the value MQ checks for OAM (security) depends on another property of the configuration, specifically the CONNAUTH AUTHINFO object's ADOPTCTX attribute.  If this is set to NO, MQ still checks OAM against the use the process that made the connection was running under.  This is the default for all v8 and v9.0.0.x LTS and v9.0.1 - 9.0.4 CD.  v9.0.5 CD and v9.1.0.x LTS and v9.1.x CD changed this to have the default of YES which means the user that is successfully authenticated is what is checked against OAM.

IBM Fix Readme [Behavioural changes to MQ client connections introduced by APAR IT25839](https://www-01.ibm.com/support/docview.wss?uid=ibm10725873) gives a good illustration of the complexity around what happens on the queue manager side, but does illustrate the most current behavior, note the only release that at this point has these security exit related changes is 9.0.0.5 LTS which was just released by IBM on Aug 30th, v8 and v9.1 will not have this APAR until the next release.

**Comment by deliego** [comment]
Sorry for the delayed response, it was a long weekend here.

@JoshMcMQ Thank you so much for this explanation, I learned quite a lot from this and found out why it behaves the way it does. If I am understanding correctly, when pymqi attempts to connect, it builds a MQCSP structure which tells the queue manager to authenticate a user and password. In this case, it is expecting a value for a password and that is why it fails. I understand the security vulnerability of granting access to users without passwords but there could be some deeper authentication checking that is happening that I am not aware of. The combination I am speaking of is providing a user with blank passwords.

This brings me to a new question, if this is the case that pymqi cannot allow blank passwords to connect to MQ, why is there code in pymqi to accomodate blank passwords when authenticating? It seems like it was a use case and should handle it.

@dsuch You mentioned before this should be working as it should be able to handle blank passwords. What configuration must exist on MQ for allowing that to happen? Maybe I am missing something in my tests.

If I misunderstood something, let me know.

Thanks so much for all your help and input.

Diego

**Comment by deliego** [comment]
Hi @JoshMcMQ. Thanks again for your help, much appreciated.

I have tested configuring an OS user that accepts no password (simply create a user and blank password) and given it permissions to connect to MQ (I tried it with password first to test, connects fine, then removed password and configured user to "no password"). I, then get the error from MQ that it is not authorized. In this case, the user really allows for no password, at least on an OS level.

On the other hand, you are right in that I am able to connect without a user or password, basically not passing any user and it uses the user that the process runs on and lets me connect. This is because I have CHCKCLNT set to OPTIONAL as you stated.

I ran the command you mentioned and this is what it returned:
```
DIS AUTHINFO(SYSTEM.DEFAULT.AUTHINFO.IDPWOS) AUTHENMD ADOPTCTX
     1 : DIS AUTHINFO(SYSTEM.DEFAULT.AUTHINFO.IDPWOS) AUTHENMD ADOPTCTX
AMQ8566I: Display authentication information details.
   AUTHINFO(SYSTEM.DEFAULT.AUTHINFO.IDPWOS)
   AUTHTYPE(IDPWOS)                        ADOPTCTX(YES)
   AUTHENMD(OS)
```

In regards to my last comment before:

> > I understand the security vulnerability of granting access to users without passwords but there could be some deeper authentication checking that is happening that I am not aware of.

> If the account has no password, what type of deeper authentication checking could be going on?

I find it strange that financial, government, large retail businesses have this configuration with blank passwords when they know how sensitive their data is. This is why I said there could be another layer of authentication or configuration that I am not aware of. However, they have other applications that connect to MQ with blank passwords (providing a user of course). It's head scratching to me.

Thanks,

Diego

**Comment by JoshMcMQ** [comment]
@deliego when you have AUTHENMD(OS) MQ will call out to `/opt/mqm/bin/security/amqoamax USERNAME` and then provide the password as STDIN for the process.  If you had AUTHENMD(PAM) MQ will call out to `/opt/mqm/bin/security/amqoamax USERNAME` and then provide the password as STDIN for the process.

I do not have a user with no password to test myself, but providing a blank password failed in various ways when I directly tested with these programs that MQ calls.  The `-n` in my example tells echo not to send a new line which is likely how MQ calls this program and as you can see in the case of both ax and px versions it dies with a Memory fault.

    $echo -n ''|/opt/mqm/bin/security/amqoamax testuser
    -ksh: 23573: Memory fault
    Memory fault
    $echo -n ''|/opt/mqm/bin/security/amqoampx testuser
    -ksh: 23577: Memory fault
    Memory fault
    $echo ''|/opt/mqm/bin/security/amqoamax testuser
    -2035 [FAILED]
    $echo ''|/opt/mqm/bin/security/amqoampx testuser
    -19 [Conversation error]

The following is am example of the good output of the px program:

    $echo -n GOODPASS|/opt/mqm/bin/security/amqoampx testuser
    +0 [NULL]

You could try to open a PMR with IBM and ask them to review your test case with blank password, but they may just say that it is working as designed.

---

As to why financial, government, and large retail businesses may have this configuration is not something I cam comment on,  I'm not a mind reader.

I can say that I would never recommend this.  I would also hope that with the current state of threats that this would hopefully be less of a issue now than in the past.

**Comment by deliego** [comment]
@dsuch Have you tested this with a blank password? The code in __init__.py says:
```
if user:
            # We check for None because password can be an empty string
            if password is None:
                raise ValueError('Password must not be None if user is provided')

            if not (isinstance(user, (str, bytes)) and isinstance(password, (str, bytes))):
                raise ValueError('Both user and password must be instances of str or bytes')

            user_password['user'] = py3str2bytes(user, 'utf-8')
            user_password['password'] = py3str2bytes(password, 'utf-8')
```

I'm wondering if it can accept it or not.

99% of the business I have been dealing with use no password. When I ask them that a user/password must be provided they are not receptive of this as it is not the recommended approach. I have tried explaining what @JoshMcMQ has explained but password protection is still not the recommended approach.

IBM states: "For production purposes, you should use TLS encryption in preference to IBM MQ password protection, especially when the network between the client and queue manager is untrusted, as TLS encryption is more secure."
"SSL encryption is still the preferred method over WebSphere MQ password protection, especially when the network between the client and queue manager is untrusted, as SSL/TLS encryption is more secure. Password protection mechanism is suitable for the customers who don't use SSL as this overheads with certificate management."

Have you been able to test this without any password? (username provided)

Thanks,

Diego

**Comment by dsuch** [comment]
Hi @deliego,

yes, a few months ago I sent a username and an empty password and I confirmed it under Wireshark, there was no password sent. I am not 100% clear what else you would like to confirm / test?

Regards.

**Comment by JoshMcMQ** [comment]
@deliego Did you see my update from Sep 11?   I showed that the underlying program that MQ calls to perform the authentication likely does not accept a null password, you can run those commands I listed and confirm this yourself, try both of the commands below while specifying the user that you setup with no password (Note with `AUTHENMD(OS)` IBM MQ calls out to the `amqoamax` program):

    echo -n ''|/opt/mqm/bin/security/amqoamax testuser
    echo ''|/opt/mqm/bin/security/amqoamax testuser

Assuming the above fails with any output other than `+0 [NULL]` then changing pymqi to send a MQCSP that has a user filled in and a null password would make no difference at this time as IBM MQ does not accept a null password even if sent.

---

In regards to the two statements you provide from IBM to try and show that IBM does not recommend CONNAUTH, you are misunderstanding what they are stating.  Password protection is a specific component of the IBM MQ CONNAUTH and only refers to how the actual password field of the MQCSP structure is "protected" while it is transferred across the network.
1. If the IBM MQ SVRCONN channel is configured with a SSLCIPH value that is a non-NULL cipherspec then password protection does not come into play as the password itself is "protected" by the TLS encryption of the channel.
2. If the IBM MQ SVRCONN channel is not configured with a SSLCIPH value or the value is a NULL cipherspec then the MQ v8 and later will default to "protect" the password by not sending it in the clear and instead provide some level of encryption of the password value as it is transferred across the network.

---

Specifically you reference this statement:
> For production purposes, you should use TLS encryption in preference to IBM MQ password protection, especially when the network between the client and queue manager is untrusted, as TLS encryption is more secure.

That is directly from the IBM Knowledge center they page [Security>Security overview>IBM MQ security mechanisms>Security protocols in IBM MQ>MQCSP password protection](https://www.ibm.com/support/knowledgecenter/en/SSFKSJ_8.0.0/com.ibm.mq.sec.doc/q118710_.htm), you failed to mention on that same page that it specifically states the following right at the top:

> From IBM® MQ Version 8.0 , you can send passwords that are included in the MQCSP structure either **protected, by using IBM MQ functionality**, or encrypted, by using SSL/TLS encryption.

It also goes on to state the following:
> If you are concerned precisely **what encryption is being used, and how much protection it offers, you need to use full TLS encryption.** In this situation, the algorithms are publicly known, and you can select the appropriate one for your enterprise by using the SSLCIPH channel attribute.

This page is not saying that CONNAUTH is not recommended, it is recommending the use of TLS to encrypt your connection to the queue manager to protect the password being transferred across the network instead of relying on the MQ builtin password protection functionality.  See below for more on this.

---

You also reference this statement:
> SSL encryption is still the preferred method over WebSphere MQ password protection, especially when the network between the client and queue manager is untrusted, as SSL/TLS encryption is more secure. Password protection mechanism is suitable for the customers who don't use SSL as this overheads with certificate management.

That is directly from the a blog by Girish D V at IBM titled [MQCSP Password Protection in MQ V8](https://www.ibm.com/developerworks/community/blogs/messaging/entry/websphere_mqcsp_password_protection_in_mq_v8?lang=en).

Girish also states the following:
>Prior to Websphere MQ version 8 the passwords from client to the queue manager were sent across the network in plain text if SSL/TLS encryption is not used which is insecure. MQ version 8 provides options to send passwords that are included in the MQCSP structure **protected by using websphere MQ functionality** or by using SSL/TLS encryption.

It also states the following:
>MQ version 8 provides supports 2 password protection algorithms
-"null" algorithm which sends password as plain text which is seen in all MQ versions
-"real" password protection algorithm which uses **Triple DES(3DES)** based encryption.

---

IBM does not officially document the encryption algorithm used for MQ's password protection functionality in the IBM MQ Knowledge center, but the BLOG post you referenced does reveal that it is using the 3DES algorithm which depending on your company's information security standards may not be sufficient.

IBM's suggestion is that if you care what encryption algorithm is used to keep your password from being transferred across the network in the clear, then use TLS on the channel, don't rely on MQ's password protection.  They are not saying that MQ CONNAUTH is not recommended which is what you seem to be taking from the comments.

I agree with what IBM says and my recommendation if you want to use CONNAUTH is to set up the SVRCONN channel with `SSLCAUTH(OPTIONAL)`, in this way the client side can specify a `kdb` file that only needs to contain the root CA that signed the queue manager's cert.  The entire network connection from the client to the server is then encrypted including the password that is sent across the connection to MQ, in this way "Password Protection" does not even come into play as TLS is proving the protection of the password.

Again "Password Protection" != CONNAUTH.

---

>99% of the business I have been dealing with use no password. When I ask them that a user/password must be provided they are not receptive of this as it is not the recommended approach. I have tried explaining what @JoshMcMQ has explained but password protection is still not the recommended approach.

I still wonder who would think that zero authentication is recommended over having authentication.

I will quote the same thing I stated on my first response on Sep 1st:
>It would be much better to send a username and password that will be validated, or use client TLS certificates to assert identity (When combined with setting the channels SSLPEER and a MCAUSER (or a CHLAUTH SSLPEERMAP rule) you can greatly restrict who can connect to your channel, and you eliminate the ability for them to assert any arbitrary username.

As mentioned the two out of the box methods for a MQ queue manager to validate the client that is connecting to the queue manager are for the client to present a certificate and the queue manager to validate this and map it to a MCAUSER, or for the client to send a username and password and for MQ to validate this username and password.

**Comment by dsuch** [comment]
@deliego By the way, it is also my experience that most MQ users do not employ any passwords or transport-level security (TLS) at all, I understand what you are saying.

But I think you might have missed one of my responses (Sep 1, 2018) where I said that using PyMQI 1.8.0 I successfully sent a username with no password.

**Comment by JoshMcMQ** [comment]
@dsuch as stated earlier in one of my comments if you do not pass a MQCSP at all the user running the process is sent to MQ with no password.  If you look at the code @deliego quoted yesterday if you specify no password the MQCSP is not sent.  Based on the testing I did even if you changed it to send a NULL password MQ would still fail on this but as I said I do not have a user with no password to test against so advised @deliego to test out the low level MQ commands to see if it would even accept a null password.

**Comment by dsuch** [comment]
> If you look at the code @deliego quoted yesterday if you specify no password the MQCSP is not sent.

Right, but there is a difference between not providing a password at all (password=None) and providing an empty one (password='').

I'm quite confident that when I checked it back in August, the latter variant produced a wire-level message with a username but without a password, as confirmed under Wireshark.

**Comment by dsuch** [comment]
@deliego @JoshMcMQ But just to confirm it - I am only saying that PyMQI does allow for an empty/blank password and will send it down the wire.

I do not know what MQ does with such a password sent from a non-Java application because, just like @JoshMcMQ, I do not have any MQ environment matching the one that @deliego uses.

**Comment by JoshMcMQ** [comment]
@dsuch, thank you for the info on the difference between `password=None` vs `password=''`, I was not catching that subtlety.

With that being said, I while still don't have access to test against a unix user that allows for no password on an OS level, I was able to tell that when passing a MQCSP with a empty password, the queue manager does call out to the `amqoamax` program and passes it a empty password with a new line.

@deliego Based on the testing I did the following command should test how MQ calls out to the underlying `amqoamax` programe to authenticate the user:

    echo ''|/opt/mqm/bin/security/amqoamax testuser

The output from the `amqoamax` when it is successful is:

    +0 [OK]

When it fails it will be:

    -2035 [FAILED]

---

If the above test is successful then as @dsuch stated you just need to pass `password=''`, but this appears to be what you stated you tried when you opened this issue.  I would suggest making sure you have pymqi 1.8 instead of 1.7.2.

Note I tested that MQ 8.0.0.10 passed the empty password to the `amqoamax` program, you were using 9.0.5 so things may be different.

---

In the end, since you don't want to check a password, then I think it is far simpler to just run the program as the user you want to assert and not set user or password in your pymqi code.

**Comment by dsuch** [comment]
Closing due to inactivity - I think this was a great an enlightening discussion!

**Comment by kenkitts** [comment]
Great conversation.  This saved me a tremendous headache in trying to figure out why my personal userid, under which I run Python, was being sent as the user.

**Comment by JoshMcMQ** [comment]
@deliego I know this is a old closed thread, but I wanted to know the outcome if you were ever able to test the following,  based on the testing I did the following command should test how MQ calls out to the underlying `amqoamax` program to authenticate the user (replace `testuser` with the actual username that has no password on Linux):

    echo ''|/opt/mqm/bin/security/amqoamax testuser

The output from the `amqoamax` when it is successful is:

    +0 [OK]

When it fails it will be:

    -2035 [FAILED]

**Comment by deliego-github** [comment]
Hi @JoshMcMQ, we gave up and just told users to configure authentication to either not authenticate, or if they pass a user, to always pass a password.

**Comment by 2020testuser** [comment]
@JoshMCMQ - Could you please provide information on what solution worked? I have the same issue. Even disabling authentication both on the MQClient and Server side , didn't work. I'm having MQClient, python package and a sample program in my Dockerfile. Any help or info. would be greatly usefulf or me. Thanks in advance!

**Comment by JoshMcMQ** [comment]
@deliego-github IBM released a new APAR that sounds like it will fix the issue authenticating a user which has a blank password.

[IT38146: When using CONNAUTH TYPE(IDPWOS) the queue manager is unable to authenticate a user account with no password](https://www.ibm.com/support/pages/apar/IT38146)

It says this is fixed in the following releases:

```
Version    Maintenance Level
v9.0 LTS   9.0.0.13
v9.1 LTS   9.1.0.11
v9.x CD    9.2.5
```

**Comment by deliego** [comment]
Thanks @JoshMcMQ for the info. Good to know they identified it and will fix it
