### ISSUE TITLE
MQRC_CHANNEL_CONFIG_ERROR

### ISSUE THREAD

**Issue by linuxdavidwu** [dsuch/pymqi#82]
iibmmq:9.0
python:3.6
pymqi1.8.0

D:\ProgramData\Anaconda3\envs\project\python.exe "D:/Program Files/project/venv/ibmmq.py"
Traceback (most recent call last):
  File "D:/Program Files/project/venv/ibmmq.py", line 7, in <module>
    qmgr = pymqi.connect('topplus.queue.manager', 'TOPDCT.TO.EPC.CHL', '10.11.11.171(1414)',user,password)
  File "D:\ProgramData\Anaconda3\envs\project\lib\site-packages\pymqi\__init__.py", line 2604, in connect
    qmgr.connect_tcp_client(queue_manager or '', CD(), channel, conn_info, user, password)
  File "D:\ProgramData\Anaconda3\envs\project\lib\site-packages\pymqi\__init__.py", line 1447, in connect_tcp_client
    self.connect_with_options(name, cd, user=user, password=password)
  File "D:\ProgramData\Anaconda3\envs\project\lib\site-packages\pymqi\__init__.py", line 1429, in connect_with_options
    raise MQMIError(rv[1], rv[2])
pymqi.MQMIError: MQI Error. Comp: 2, Reason 2539: FAILED: MQRC_CHANNEL_CONFIG_ERROR

imq:9.0
python:3.

import pymqi

user= 'None'
password = 'None'

qmgr = pymqi.connect('topplus.queue.manager', 'TOP.TO.EPC.CHL', '10.11.11.171(1414)',user,password)

que = pymqi.Queue(qmgr, 'topepc_cntrevents.remote.queue')
que.put("test_msg")
que.get()

que.close()
qmgr.disconnect()

**Comment by dsuch** [comment]
Hello @linuxdavidwu,

thank you for opening the ticket but this is not a message generated by PyMQI. Instead, it was returned to PyMQI from the MQ layer.

In these circumstances, I am closing the ticket.
