### ISSUE TITLE
Connect via ssl with alternative username

### ISSUE THREAD

**Issue by DennyD17** [dsuch/pymqi#87]
Hello!
I'm using pymqi with windows 7 and python 2.7.
I use that code to connect to queue manager with ssl:

````
class MQConnection(object):

    def __init__(self):
        channel = "OD.SVRCONN"
        host = "10.111.11.111"
        port = "1311"
        self.put_queue_name = "IN"
        self.get_queue_name = "OUT"
        self.put_notify_queue_name = "RESPONSE"
        self.get_notify_queue_name = "REQUEST"
        conn_info = "%s(%s)" % (host, port)
        ssl_cipher_spec = 'TLS_RSA_WITH_AES_128_CBC_SHA256'
        key_repo_location = r"C:\Users\**denis**\workspace\mq\repo\**mquser**
        cd = pymqi.CD()
        cd.ChannelName = channel
        cd.ConnectionName = conn_info
        cd.ChannelType = pymqi.CMQC.MQCHT_CLNTCONN
        cd.TransportType = pymqi.CMQC.MQXPT_TCP
        cd.SSLCipherSpec = ssl_cipher_spec
        sco = pymqi.SCO()
        sco.KeyRepository = key_repo_location
        queue_manager = "GATEWAY.CLS2"
        od = pymqi.od()
        self.qmgr = pymqi.QueueManager(None)
        self.qmgr.connect_with_options(queue_manager, cd, sco, od)
````

When i use operation system user "mquser" (as my mq user and as ssl repo files named) everything works fine. 
But when I try to run the same code with another os user ("denis" at example) I get mq error 
"2393 mqrc_ssl_initialization_error" from mqserver and "AMQ9660" in client logs.
When I ran my app on unix system with root I have the same error.

I cant develop using mquser os user.

Can you help me ?

**Comment by JoshMcMQ** [comment]
MQ finds the certificate in the keystore to use when connecting by default based on the cert label.  As a default it will attempt to find a cert with a label of `ibmwebspheremq<username in lowercase>`.  So if you run as a user `mquser` it would look for `ibmwebspheremqmquser`, if you run as a user `denis` it will look for `ibmwebspheremqdenis`.

You can use the `runmqakm` command supplied with MQ client v7.1 and later to rename the cert label to the value required.

If you are using v8.0 or later you can specify the `sco.CertificateLabel = "ibmwebspheremqmquser"`.  This way the key store would work for either user.

For much more detail about the how MQ interacts with the cert label please review the following IBM Technote: [Specifying the userid in the SSL certificate label for an MQ client](https://www-01.ibm.com/support/docview.wss?uid=swg21245474)

Please mark this as closed if this resolves your problem or let me know if you have further questions.

**Comment by dsuch** [comment]
Closing due to inactivity - @DennyD17, if @JoshMcMQ's answer has not sufficed, please feel free to reopen.

**Comment by DennyD17** [comment]
Hello! 
I can't to test it because it was only 7.0.1 version available for me.
I tested it now.

My MQ client version is 9.0.0.3-IBM-MQC-LinuxX64
Applications works in container, orchestra is Openshift 3.0.

 **Cert reqs was created by the following command:**
`runmqckm -certreq -create -db od99usr.kdb -pw pw -label ibmwebspheremqod99usr -dn dn -size 2048 -file od99usr.csr -sig_alg SHA256WithRSA
`

**Part of code from my application:**
```
ssl_cipher_spec = 'TLS_RSA_WITH_AES_128_CBC_SHA256'
# MQ
cd = pymqi.CD()
cd.ChannelName = channel
cd.ConnectionName = conn_info
cd.ChannelType = pymqi.CMQC.MQCHT_CLNTCONN
cd.TransportType = pymqi.CMQC.MQXPT_TCP
cd.SSLCipherSpec = ssl_cipher_spec
cd.CertificateLabel = "ibmwebspheremqod99usr"
# SCO
sco = pymqi.SCO()
sco.CertificateLabel = "ibmwebspheremqod99usr"
sco.KeyRepository = key_repo_location

```

**Whoaim from container:**

```
whoami
whoami: cannot find name for user ID 1007400000

```
**when I trying to connect I get the following python error:**

```
Traceback (most recent call last):

  File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 385, in trace_task

    R = retval = fun(*args, **kwargs)

  File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 648, in __protected_call__

    return self.run(*args, **kwargs)

  File "/code/base/tasks.py", line 22, in get_create_incident_results

    mq = MQConnection()

  File "/code/base/mq.py", line 39, in __init__

    self.qmgr.connect_with_options(queue_manager, cd, sco)

  File "/usr/local/lib64/python3.6/site-packages/pymqi/__init__.py", line 1412, in connectWithOptions

    raise MQMIError(rv[1], rv[2])

pymqi.MQMIError: MQI Error. Comp: 2, Reason 2381: FAILED: MQRC_KEY_REPOSITORY_ERROR
```

In /var/mqm/errors/*log I have:

```
----- amqxfdcx.c : 891 --------------------------------------------------------
04/21/2020 03:27:36 PM - Process(37.1) User(UNKNOWN) Program(celery)
                    Host(sdsa-47-4rgwt) Installation(Installation1)
                    VRMF(9.0.0.3) QMgr(.)
 
AMQ9627: The path and stem name for the SSL key repository have not been
specified.
 
EXPLANATION:
The directory path and file stem name for the SSL key repository have not been
specified. On a MQ client system there is no default location for this file.
SSL connectivity is therefore impossible as this file cannot be accessed.
ACTION:
Use the MQSSLKEYR environment variable or MQCONNX API call to specify the
directory path and file stem name for the SSL key repository.

```

Can you explain me where is my mistake?
I also tried to change 
sco.CertificateLabel to "od99usr"
remove and add cd.CertificateLabel
but get the same error =(

> Hi @DennyD17,
> 
> MQ finds the certificate in the keystore to use when connecting by default based on the cert label. As a default it will attempt to find a cert with a label of `ibmwebspheremq<username in lowercase>`. So if you run as a user `mquser` it would look for `ibmwebspheremqmquser`, if you run as a user `denis` it will look for `ibmwebspheremqdenis`.
> 
> You can use the `runmqakm` command supplied with MQ client v7.1 and later to rename the cert label to the value required.
> 
> If you are using v8.0 or later you can specify the `sco.CertificateLabel = "ibmwebspheremqmquser"`. This way the key store would work for either user.
> 
> For much more detail about the how MQ interacts with the cert label please review the following IBM Technote: [Specifying the userid in the SSL certificate label for an MQ client](https://www-01.ibm.com/support/docview.wss?uid=swg21245474)
> 
> Please mark this as closed if this resolves your problem or let me know if you have further questions.
