### ISSUE TITLE
PyInstaller packing issue

### ISSUE THREAD

**Issue by tsunawang** [dsuch/pymqi#98]
Hi, I'm using pyinstaller to pack my python script into exe file.

But I keep getting error message while executing it.

My python script simply imports pymqi, nothing else.

Packing command :
>>  pyinstaller pythonTest.py

After successfully packed. 

Below is the error message while execute
---------------------------
AMQ6290: Unknown installation 'C:\src_py\mqExeTest\dist\pythonTest' detected.
Traceback (most recent call last):
  File "pymqi\__init__.py", line 110, in <module>
ImportError: DLL load failed: 動態連結程式庫 (DLL) 初始化例行程序失敗。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pythonTest.py", line 4, in <module>
    import pymqi
  File "c:\users\aaa\appdata\local\programs\python\python37-32\lib\site-packages\pyinstaller-3.5.dev0+80bd962c3-py3.7.egg\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "pymqi\__init__.py", line 112, in <module>
ImportError: DLL load failed: 發生內部錯誤。
[19776] Failed to execute script pythonTest

-----------------------------

**Comment by dsuch** [comment]
Hello @tsunawang,

it looks that MQ DLLs can not be found when PyMQI is wrapped in a PyInstaller-based exe file. I do not use Windows and I have never used PyInstaller so I do not have any immediate remedy.

Is there anything perhaps in PyInstaller's documentation about how to prepare packages that call C-based libraries with DLL? Maybe it requires some additional configuration or tweaking to be able to find DLLs?

Regards.

**Comment by tsunawang** [comment]
@dsuch  I've tried --hidden-import  for  'pymqe', but still got the same error message

**Comment by dsuch** [comment]
Hi @tsunawang,

I understand it but this is more of a PyInstaller question - how to configure it to ensure it can find DLLs needed - so I suggest that you inquire about it among PyInstaller users.

When you learn how to do it - please leave a message here so that in the future other users will be able find it.

Thanks.

**Comment by dsuch** [comment]
No activity, closing the ticket.
